channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.65.0
- google-auth =2.14.0
- google-auth-oauthlib =0.7.1
- tqdm =4.64.1
- pandas =1.5.1
- sqlalchemy =1.4.42
- numpy =1.23.4
- pydatamail =0.0.10
