channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.44.0
- google-auth =2.6.5
- google-auth-oauthlib =0.5.1
- tqdm =4.64.0
- pandas =1.4.2
- sqlalchemy =1.4.35
- numpy =1.22.3
- matplotlib =3.5.1
- pydatamail =0.0.4
