channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.61.0
- google-auth =2.11.1
- google-auth-oauthlib =0.5.3
- tqdm =4.64.1
- pandas =1.5.0
- sqlalchemy =1.4.41
- numpy =1.23.3
- pydatamail =0.0.10
