channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.42.0
- google-auth =2.6.2
- google-auth-oauthlib =0.5.1
- tqdm =4.63.1
- pandas =1.4.1
- sqlalchemy =1.4.33
- numpy =1.22.3
- matplotlib =3.5.1
- pydatamail =0.0.4
