channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.52.0
- google-auth =2.9.0
- google-auth-oauthlib =0.5.2
- tqdm =4.64.0
- pandas =1.4.3
- sqlalchemy =1.4.39
- numpy =1.23.0
- matplotlib =3.5.2
- pydatamail =0.0.8
