channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.57.0
- google-auth =2.11.0
- google-auth-oauthlib =0.5.2
- tqdm =4.64.1
- pandas =1.4.3
- sqlalchemy =1.4.40
- numpy =1.23.1
- pydatamail =0.0.10
