channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.41.0
- google-auth =2.6.0
- google-auth-oauthlib =0.5.1
- tqdm =4.63.0
- pandas =1.4.1
- sqlalchemy =1.4.32
- numpy =1.22.3
- matplotlib =3.5.1
- pydatamail =0.0.4
