channels:
- conda-forge
dependencies:
- python
- coverage
- coveralls
- google-api-python-client =2.49.0
- google-auth =2.6.6
- google-auth-oauthlib =0.5.1
- tqdm =4.64.0
- pandas =1.4.2
- sqlalchemy =1.4.36
- numpy =1.22.4
- matplotlib =3.5.2
- pydatamail =0.0.4
